# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CLZ_mOpSzP-Rb-86jmnEdQ-qt4utu7da
"""

import numpy as num
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/instagram_usage_lifestyle.csv")

df

df.info()

df.describe().astype(int)

df.isnull().sum()

df[df.isnull().any(axis=1)]

df.drop(3720,inplace=True)

df.drop(7428,inplace=True)

df[df.isnull().any(axis=1)]

df.isnull().sum()

df[["age","time_on_feed_per_day"]].plot(kind="box")

df["time_on_feed_per_day"].max()

df.describe().astype(int)

df[["age","perceived_stress_score"]].plot(kind="box")